# Generated by Django 3.2.5 on 2022-05-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('brief_concent', models.TextField()),
                ('concent', models.TextField()),
                ('publish_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
